### PR TITLE
Add time operations feature to calculator

### PR DESCRIPTION
**Pull request by SamuelSVG**
The time operations feature is finished and can now be added to the dev branch.

### CODE REVIEW

**Review by MarineB210 — CHANGES_REQUESTED** [review]
Please fix the conflicts issues and failed tests. Thank you.

**Review by NosalVictor — APPROVED** [review]

**Comment by SamuelSVG** [comment]
> Please fix the conflicts issues and failed tests. Thank you.

The issue should now be fixed.

**Comment by MarineB210** [comment]
> > Please fix the conflicts issues and failed tests. Thank you.
> 
> The issue should now be fixed.

THE ISSUE WAS NOT FIXED !!!

**Review by MarineB210 — APPROVED** [review]
Finally, something that works 
74f4f548392fbdafbe8a5d9764c83eaf

**Pull request merged**
